---
- hosts: 172.31.20.82
  become: yes
  tasks:
  - name: i want to execute linux command directly
    command: hostname
    register: myresult
  - name: i want to display myresult
    debug: 
      msg: "{{myresult}}"