---
- hosts: 172.31.20.82
  become: yes
  tasks:
  - name: i want to install git
    apt:
      name: git
      state: present
  - name: i want to install tree
    apt:
      name: tree
      statees: present
  - name: i want to install wget
    apt:
      name: wget
      state: present