---
- hosts: 172.31.20.82
  become: yes
  tasks:
  - include_tasks: files.yaml

  - name: i wnat to install webserver on ubuntu node
    apt:
     name: apache2
     state: present
    notify: restartwebserver

  - name: i want to copy myindex.j2 into node side 
    template:
      src: myindex.j2
      dest: /var/www/html/index.
    notify: restartwebserver

  handlers:
   - name:  restartwebserver 
     service:
      name: apache2
      state: restarted





