---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install websever on debian nodes only
    apt:
     name: "{{mywebpackageforubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install webserver on RedHat nodes only
    yum:
     name: "{{mywebpackageforredhat}}"
     state: present
    when: ansible_os_family =="RedHat"