---
- hosts: all
  become: yes
  tasks:
  - name: install websever on debian nodes only
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
    
  - name: install webserver on RedHat nodes only
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"